# ///////////////////////////////////////////////////////////////
# SHARED.RESOURCES - Shared resource definitions
# Project: ezqt_app
# ///////////////////////////////////////////////////////////////

"""Shared static resource path definitions."""

from __future__ import annotations

# ///////////////////////////////////////////////////////////////
# IMPORTS
# ///////////////////////////////////////////////////////////////
import importlib.util
import logging
import sys
from pathlib import Path
from types import ModuleType
from typing import Any  # noqa: F401  # pyright: ignore[reportUnusedImport]

# Local imports
from ...resources import base_resources_rc  # type: ignore # noqa: F401
from ...utils.runtime_paths import get_bin_path
from .icons import Icons as _PackageIcons
from .images import Images as _PackageImages

Icons = _PackageIcons
Images = _PackageImages

# Typed accessors for user-compiled resources — populated by load_runtime_rc().
# Typed as Any: attributes are generated dynamically from bin/app_icons.py.
#
# WARNING — import pattern:
#   Always access via the module, not via a direct import, to ensure the
#   reference stays live after load_runtime_rc() reassigns the variable:
#
#     ✅  from ezqt_app.shared import resources; resources.AppIcons.my_icon
#     ✅  from ezqt_app.shared.resources import AppIcons  (only after init())
#     ❌  from ezqt_app.shared.resources import AppIcons  (at module top-level,
#          before init() — captures None and never updates)
AppIcons: Any = None
AppImages: Any = None


def _load_module_from_file(module_name: str, file_path: Path) -> ModuleType | None:
    """Import a Python module directly from file when it exists."""
    if not file_path.exists() or not file_path.is_file():
        return None

    spec = importlib.util.spec_from_file_location(module_name, file_path)
    if spec is None or spec.loader is None:
        return None

    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except Exception as e:
        logging.getLogger(__name__).warning(
            "Failed to load runtime module %s from %s: %s", module_name, file_path, e
        )
        return None

    sys.modules[module_name] = module
    return module


# Best-effort loads at import time: succeed when the files already exist from
# a previous init() run, silently skipped otherwise.
_load_module_from_file(
    "ezqt_app._runtime_resources_rc", get_bin_path() / "resources_rc.py"
)
_icons_mod = _load_module_from_file(
    "ezqt_app._runtime_app_icons", get_bin_path() / "app_icons.py"
)
if _icons_mod is not None:
    AppIcons = getattr(_icons_mod, "AppIcons", None)

_images_mod = _load_module_from_file(
    "ezqt_app._runtime_app_images", get_bin_path() / "app_images.py"
)
if _images_mod is not None:
    AppImages = getattr(_images_mod, "AppImages", None)


def load_runtime_rc() -> None:
    """Load (or reload) the project ``resources_rc.py`` generated by init().

    Also loads ``bin/app_icons.py`` and ``bin/app_images.py`` into
    :data:`AppIcons` and :data:`AppImages` when present.

    Called by the bootstrap sequence after QRC compilation so that user assets
    are registered even when init() runs for the first time (i.e. when the
    files did not exist at import time).

    Note:
        This function reassigns the module-level :data:`AppIcons` and
        :data:`AppImages` variables.  Code that imported these symbols
        *before* ``init()`` was called holds a stale ``None`` reference.
        Access them via the module after ``init()`` to get the live value::

            # Correct — resolved at access time
            from ezqt_app.shared import resources
            icon_path = resources.AppIcons.my_icon

            # Also correct when called after init()
            from ezqt_app.shared.resources import AppIcons
            icon_path = AppIcons.my_icon
    """
    global AppIcons, AppImages  # noqa: PLW0603

    module_name = "ezqt_app._runtime_resources_rc"
    sys.modules.pop(module_name, None)
    _load_module_from_file(module_name, get_bin_path() / "resources_rc.py")

    sys.modules.pop("ezqt_app._runtime_app_icons", None)
    icons_mod = _load_module_from_file(
        "ezqt_app._runtime_app_icons", get_bin_path() / "app_icons.py"
    )
    if icons_mod is not None:
        AppIcons = getattr(icons_mod, "AppIcons", None)

    sys.modules.pop("ezqt_app._runtime_app_images", None)
    images_mod = _load_module_from_file(
        "ezqt_app._runtime_app_images", get_bin_path() / "app_images.py"
    )
    if images_mod is not None:
        AppImages = getattr(images_mod, "AppImages", None)


# ///////////////////////////////////////////////////////////////
# PUBLIC API
# ///////////////////////////////////////////////////////////////
__all__ = ["Icons", "Images", "AppIcons", "AppImages", "load_runtime_rc"]
