# ///////////////////////////////////////////////////////////////
# SHARED.RESOURCES.ICONS - Icons registry
# Project: ezqt_app
# ///////////////////////////////////////////////////////////////

"""
Shared icon resource registry.
"""

from __future__ import annotations

# ///////////////////////////////////////////////////////////////
# CLASSES
# ///////////////////////////////////////////////////////////////


class Icons:
    """
    Application icon management class.

    This class contains paths to all icons
    used in the application, organized by category.
    """

    # ////// CORE ICONS
    icon_close: str = ":/icons/icon_close.png"
    icon_maximize: str = ":/icons/icon_maximize.png"
    icon_menu: str = ":/icons/icon_menu.png"
    icon_minimize: str = ":/icons/icon_minimize.png"
    icon_restore: str = ":/icons/icon_restore.png"
    icon_settings: str = ":/icons/icon_settings.png"

    # ////// MATERIAL ICONS
    material_circled_C: str = ":/icons/material-circled-C.png"
    material_circled_K: str = ":/icons/material-circled-K.png"
    material_copy_24: str = ":/icons/material-copy-24.png"
    material_electricity: str = ":/icons/material-electricity.png"
    material_play_blue: str = ":/icons/material-play-blue.png"
    material_stop_red: str = ":/icons/material-stop-red.png"

    # ////// CIL ICONS - ARROWS
    cil_arrow_bottom_2: str = ":/icons/cil-arrow-bottom-2.png"
    cil_arrow_bottom: str = ":/icons/cil-arrow-bottom.png"
    cil_arrow_circle_bottom: str = ":/icons/cil-arrow-circle-bottom.png"
    cil_arrow_circle_left: str = ":/icons/cil-arrow-circle-left.png"
    cil_arrow_circle_right: str = ":/icons/cil-arrow-circle-right.png"
    cil_arrow_circle_top: str = ":/icons/cil-arrow-circle-top.png"
    cil_arrow_left: str = ":/icons/cil-arrow-left.png"
    cil_arrow_right: str = ":/icons/cil-arrow-right.png"
    cil_arrow_top: str = ":/icons/cil-arrow-top.png"

    # ////// CIL ICONS - NAVIGATION
    cil_chevron_bottom: str = ":/icons/cil-chevron-bottom.png"
    cil_chevron_circle_down_alt: str = ":/icons/cil-chevron-circle-down-alt.png"
    cil_chevron_circle_left_alt: str = ":/icons/cil-chevron-circle-left-alt.png"
    cil_chevron_circle_right_alt: str = ":/icons/cil-chevron-circle-right-alt.png"
    cil_chevron_circle_up_alt: str = ":/icons/cil-chevron-circle-up-alt.png"
    cil_chevron_double_down: str = ":/icons/cil-chevron-double-down.png"
    cil_chevron_double_left: str = ":/icons/cil-chevron-double-left.png"
    cil_chevron_double_right: str = ":/icons/cil-chevron-double-right.png"
    cil_chevron_double_up_alt: str = ":/icons/cil-chevron-double-up-alt.png"
    cil_chevron_double_up: str = ":/icons/cil-chevron-double-up.png"
    cil_chevron_left: str = ":/icons/cil-chevron-left.png"
    cil_chevron_right: str = ":/icons/cil-chevron-right.png"
    cil_chevron_top: str = ":/icons/cil-chevron-top.png"

    # ////// CIL ICONS - ACTIONS
    cil_action_redo: str = ":/icons/cil-action-redo.png"
    cil_action_undo: str = ":/icons/cil-action-undo.png"
    cil_check_alt: str = ":/icons/cil-check-alt.png"
    cil_check_circle: str = ":/icons/cil-check-circle.png"
    cil_check: str = ":/icons/cil-check.png"
    cil_minus: str = ":/icons/cil-minus.png"
    cil_plus: str = ":/icons/cil-plus.png"
    cil_x_circle: str = ":/icons/cil-x-circle.png"
    cil_x: str = ":/icons/cil-x.png"

    # ////// CIL ICONS - ALIGNMENT
    cil_align_center: str = ":/icons/cil-align-center.png"
    cil_align_left: str = ":/icons/cil-align-left.png"
    cil_align_right: str = ":/icons/cil-align-right.png"
    cil_justify_center: str = ":/icons/cil-justify-center.png"
    cil_justify_left: str = ":/icons/cil-justify-left.png"
    cil_justify_right: str = ":/icons/cil-justify-right.png"

    # ////// CIL ICONS - COMMUNICATION
    cil_at: str = ":/icons/cil-at.png"
    cil_chat_bubble: str = ":/icons/cil-chat-bubble.png"
    cil_comment_bubble: str = ":/icons/cil-comment-bubble.png"
    cil_comment_square: str = ":/icons/cil-comment-square.png"
    cil_envelope_closed: str = ":/icons/cil-envelope-closed.png"
    cil_envelope_letter: str = ":/icons/cil-envelope-letter.png"
    cil_envelope_open: str = ":/icons/cil-envelope-open.png"
    cil_phone: str = ":/icons/cil-phone.png"
    cil_speech: str = ":/icons/cil-speech.png"

    # ////// CIL ICONS - DEVICES
    cil_airplane_mode_off: str = ":/icons/cil-airplane-mode-off.png"
    cil_airplane_mode: str = ":/icons/cil-airplane-mode.png"
    cil_battery_0: str = ":/icons/cil-battery-0.png"
    cil_battery_3: str = ":/icons/cil-battery-3.png"
    cil_battery_5: str = ":/icons/cil-battery-5.png"
    cil_battery_alert: str = ":/icons/cil-battery-alert.png"
    cil_battery_slash: str = ":/icons/cil-battery-slash.png"
    cil_bluetooth: str = ":/icons/cil-bluetooth.png"
    cil_devices: str = ":/icons/cil-devices.png"
    cil_ethernet: str = ":/icons/cil-ethernet.png"
    cil_keyboard: str = ":/icons/cil-keyboard.png"
    cil_laptop: str = ":/icons/cil-laptop.png"
    cil_mobile_landscape: str = ":/icons/cil-mobile-landscape.png"
    cil_mobile: str = ":/icons/cil-mobile.png"
    cil_mouse: str = ":/icons/cil-mouse.png"
    cil_screen_desktop: str = ":/icons/cil-screen-desktop.png"
    cil_screen_smartphone: str = ":/icons/cil-screen-smartphone.png"
    cil_wifi_signal_0: str = ":/icons/cil-wifi-signal-0.png"
    cil_wifi_signal_1: str = ":/icons/cil-wifi-signal-1.png"
    cil_wifi_signal_2: str = ":/icons/cil-wifi-signal-2.png"
    cil_wifi_signal_4: str = ":/icons/cil-wifi-signal-4.png"
    cil_wifi_signal_off: str = ":/icons/cil-wifi-signal-off.png"

    # ////// CIL ICONS - MEDIA
    cil_3d: str = ":/icons/cil-3d.png"
    cil_4k: str = ":/icons/cil-4k.png"
    cil_camera_roll: str = ":/icons/cil-camera-roll.png"
    cil_camera: str = ":/icons/cil-camera.png"
    cil_cast: str = ":/icons/cil-cast.png"
    cil_closed_captioning: str = ":/icons/cil-closed-captioning.png"
    cil_hd: str = ":/icons/cil-hd.png"
    cil_hdr: str = ":/icons/cil-hdr.png"
    cil_headphones: str = ":/icons/cil-headphones.png"
    cil_image_plus: str = ":/icons/cil-image-plus.png"
    cil_image1: str = ":/icons/cil-image1.png"
    cil_media_eject: str = ":/icons/cil-media-eject.png"
    cil_media_pause: str = ":/icons/cil-media-pause.png"
    cil_media_play: str = ":/icons/cil-media-play.png"
    cil_media_skip_backward: str = ":/icons/cil-media-skip-backward.png"
    cil_media_skip_forward: str = ":/icons/cil-media-skip-forward.png"
    cil_media_step_backward: str = ":/icons/cil-media-step-backward.png"
    cil_media_step_forward: str = ":/icons/cil-media-step-forward.png"
    cil_media_stop: str = ":/icons/cil-media-stop.png"
    cil_movie: str = ":/icons/cil-movie.png"
    cil_speaker: str = ":/icons/cil-speaker.png"
    cil_volume_high: str = ":/icons/cil-volume-high.png"
    cil_volume_low: str = ":/icons/cil-volume-low.png"
    cil_volume_off: str = ":/icons/cil-volume-off.png"

    # ////// CIL ICONS - INTERFACE
    cil_alarm: str = ":/icons/cil-alarm.png"
    cil_ban: str = ":/icons/cil-ban.png"
    cil_bell: str = ":/icons/cil-bell.png"
    cil_briefcase: str = ":/icons/cil-briefcase.png"
    cil_browser: str = ":/icons/cil-browser.png"
    cil_calendar_check: str = ":/icons/cil-calendar-check.png"
    cil_clock: str = ":/icons/cil-clock.png"
    cil_cursor_move: str = ":/icons/cil-cursor-move.png"
    cil_cursor: str = ":/icons/cil-cursor.png"
    cil_dialpad: str = ":/icons/cil-dialpad.png"
    cil_exit_to_app: str = ":/icons/cil-exit-to-app.png"
    cil_file: str = ":/icons/cil-file.png"
    cil_folder_open: str = ":/icons/cil-folder-open.png"
    cil_folder: str = ":/icons/cil-folder.png"
    cil_home: str = ":/icons/cil-home.png"
    cil_house: str = ":/icons/cil-house.png"
    cil_menu: str = ":/icons/cil-menu.png"
    cil_notes: str = ":/icons/cil-notes.png"
    cil_options_horizontal: str = ":/icons/cil-options-horizontal.png"
    cil_options: str = ":/icons/cil-options.png"
    cil_settings: str = ":/icons/cil-settings.png"
    cil_size_grip: str = ":/icons/cil-size-grip.png"
    cil_task: str = ":/icons/cil-task.png"
    cil_terminal: str = ":/icons/cil-terminal.png"
    cil_window_maximize: str = ":/icons/cil-window-maximize.png"
    cil_window_minimize: str = ":/icons/cil-window-minimize.png"
    cil_window_restore: str = ":/icons/cil-window-restore.png"

    # ////// CIL ICONS - USERS
    cil_account_logout: str = ":/icons/cil-account-logout.png"
    cil_people: str = ":/icons/cil-people.png"
    cil_user_female: str = ":/icons/cil-user-female.png"
    cil_user_follow: str = ":/icons/cil-user-follow.png"
    cil_user_unfollow: str = ":/icons/cil-user-unfollow.png"
    cil_user: str = ":/icons/cil-user.png"

    # ////// CIL ICONS - EMOTIONS
    cil_face_dead: str = ":/icons/cil-face-dead.png"
    cil_frown: str = ":/icons/cil-frown.png"
    cil_meh: str = ":/icons/cil-meh.png"
    cil_mood_bad: str = ":/icons/cil-mood-bad.png"
    cil_mood_good: str = ":/icons/cil-mood-good.png"
    cil_mood_very_bad: str = ":/icons/cil-mood-very-bad.png"
    cil_mood_very_good: str = ":/icons/cil-mood-very-good.png"
    cil_smile: str = ":/icons/cil-smile.png"

    # ////// CIL ICONS - MISC
    cil_av_timer: str = ":/icons/cil-av-timer.png"
    cil_caret_bottom: str = ":/icons/cil-caret-bottom.png"
    cil_caret_left: str = ":/icons/cil-caret-left.png"
    cil_caret_right: str = ":/icons/cil-caret-right.png"
    cil_caret_top: str = ":/icons/cil-caret-top.png"
    cil_cart: str = ":/icons/cil-cart.png"
    cil_chart_line: str = ":/icons/cil-chart-line.png"
    cil_chart_pie: str = ":/icons/cil-chart-pie.png"
    cil_chart: str = ":/icons/cil-chart.png"
    cil_circle: str = ":/icons/cil-circle.png"
    cil_clipboard: str = ":/icons/cil-clipboard.png"
    cil_clone: str = ":/icons/cil-clone.png"
    cil_cloud_download: str = ":/icons/cil-cloud-download.png"
    cil_cloud_upload: str = ":/icons/cil-cloud-upload.png"
    cil_cloudy: str = ":/icons/cil-cloudy.png"
    cil_code: str = ":/icons/cil-code.png"
    cil_coffee: str = ":/icons/cil-coffee.png"
    cil_credit_card: str = ":/icons/cil-credit-card.png"
    cil_cut: str = ":/icons/cil-cut.png"
    cil_data_transfer_down: str = ":/icons/cil-data-transfer-down.png"
    cil_data_transfer_up: str = ":/icons/cil-data-transfer-up.png"
    cil_deaf: str = ":/icons/cil-deaf.png"
    cil_description: str = ":/icons/cil-description.png"
    cil_dog: str = ":/icons/cil-dog.png"
    cil_door: str = ":/icons/cil-door.png"
    cil_double_quote_sans_left: str = ":/icons/cil-double-quote-sans-left.png"
    cil_double_quote_sans_right: str = ":/icons/cil-double-quote-sans-right.png"
    cil_drop: str = ":/icons/cil-drop.png"
    cil_equalizer: str = ":/icons/cil-equalizer.png"
    cil_expand_down: str = ":/icons/cil-expand-down.png"
    cil_expand_left: str = ":/icons/cil-expand-left.png"
    cil_expand_right: str = ":/icons/cil-expand-right.png"
    cil_expand_up: str = ":/icons/cil-expand-up.png"
    cil_exposure: str = ":/icons/cil-exposure.png"
    cil_external_link: str = ":/icons/cil-external-link.png"
    cil_featured_playlist: str = ":/icons/cil-featured-playlist.png"
    cil_find_in_page: str = ":/icons/cil-find-in-page.png"
    cil_fingerprint: str = ":/icons/cil-fingerprint.png"
    cil_fire: str = ":/icons/cil-fire.png"
    cil_flip_to_back: str = ":/icons/cil-flip-to-back.png"
    cil_gamepad: str = ":/icons/cil-gamepad.png"
    cil_hand_point_down: str = ":/icons/cil-hand-point-down.png"
    cil_hand_point_left: str = ":/icons/cil-hand-point-left.png"
    cil_hand_point_right: str = ":/icons/cil-hand-point-right.png"
    cil_hand_point_up: str = ":/icons/cil-hand-point-up.png"
    cil_heart: str = ":/icons/cil-heart.png"
    cil_highligt: str = ":/icons/cil-highligt.png"
    cil_history: str = ":/icons/cil-history.png"
    cil_infinity: str = ":/icons/cil-infinity.png"
    cil_input_power: str = ":/icons/cil-input-power.png"
    cil_input: str = ":/icons/cil-input.png"
    cil_layers: str = ":/icons/cil-layers.png"
    cil_level_down: str = ":/icons/cil-level-down.png"
    cil_level_up: str = ":/icons/cil-level-up.png"
    cil_library_add: str = ":/icons/cil-library-add.png"
    cil_library: str = ":/icons/cil-library.png"
    cil_lightbulb: str = ":/icons/cil-lightbulb.png"
    cil_link_alt: str = ":/icons/cil-link-alt.png"
    cil_link_broken: str = ":/icons/cil-link-broken.png"
    cil_link: str = ":/icons/cil-link.png"
    cil_location_pin: str = ":/icons/cil-location-pin.png"
    cil_lock_locked: str = ":/icons/cil-lock-locked.png"
    cil_lock_unlocked: str = ":/icons/cil-lock-unlocked.png"
    cil_loop_1: str = ":/icons/cil-loop-1.png"
    cil_loop_circular: str = ":/icons/cil-loop-circular.png"
    cil_loop: str = ":/icons/cil-loop.png"
    cil_low_vision: str = ":/icons/cil-low-vision.png"
    cil_magnifying_glass: str = ":/icons/cil-magnifying-glass.png"
    cil_map: str = ":/icons/cil-map.png"
    cil_microphone: str = ":/icons/cil-microphone.png"
    cil_move: str = ":/icons/cil-move.png"
    cil_mug_tea: str = ":/icons/cil-mug-tea.png"
    cil_mug: str = ":/icons/cil-mug.png"
    cil_paint_bucket: str = ":/icons/cil-paint-bucket.png"
    cil_paper_plane: str = ":/icons/cil-paper-plane.png"
    cil_paperclip: str = ":/icons/cil-paperclip.png"
    cil_paragraph: str = ":/icons/cil-paragraph.png"
    cil_pen_alt: str = ":/icons/cil-pen-alt.png"
    cil_pencil: str = ":/icons/cil-pencil.png"
    cil_pin: str = ":/icons/cil-pin.png"
    cil_power_standby: str = ":/icons/cil-power-standby.png"
    cil_print: str = ":/icons/cil-print.png"
    cil_rectangle: str = ":/icons/cil-rectangle.png"
    cil_reload: str = ":/icons/cil-reload.png"
    cil_remove: str = ":/icons/cil-remove.png"
    cil_rss: str = ":/icons/cil-rss.png"
    cil_satelite: str = ":/icons/cil-satelite.png"
    cil_save: str = ":/icons/cil-save.png"
    cil_share_boxed: str = ":/icons/cil-share-boxed.png"
    cil_share: str = ":/icons/cil-share.png"
    cil_signal_cellular_0: str = ":/icons/cil-signal-cellular-0.png"
    cil_signal_cellular_3: str = ":/icons/cil-signal-cellular-3.png"
    cil_speedometer: str = ":/icons/cil-speedometer.png"
    cil_star: str = ":/icons/cil-star.png"
    cil_tags: str = ":/icons/cil-tags.png"
    cil_text_size: str = ":/icons/cil-text-size.png"
    cil_text_square: str = ":/icons/cil-text-square.png"
    cil_text: str = ":/icons/cil-text.png"
    cil_thumb_down: str = ":/icons/cil-thumb-down.png"
    cil_thumb_up: str = ":/icons/cil-thumb-up.png"
    cil_transfer: str = ":/icons/cil-transfer.png"
    cil_trash: str = ":/icons/cil-trash.png"
    cil_triangle: str = ":/icons/cil-triangle.png"
    cil_truck: str = ":/icons/cil-truck.png"
    cil_vertical_align_bottom: str = ":/icons/cil-vertical-align-bottom.png"
    cil_view_column: str = ":/icons/cil-view-column.png"
    cil_view_module: str = ":/icons/cil-view-module.png"
    cil_view_quilt: str = ":/icons/cil-view-quilt.png"
    cil_view_stream: str = ":/icons/cil-view-stream.png"
    cil_voice_over_record: str = ":/icons/cil-voice-over-record.png"
    cil_wallet: str = ":/icons/cil-wallet.png"
    cil_watch: str = ":/icons/cil-watch.png"
    cil_wrap_text: str = ":/icons/cil-wrap-text.png"
    cil_zoom_in: str = ":/icons/cil-zoom-in.png"
    cil_zoom_out: str = ":/icons/cil-zoom-out.png"
